<?php
namespace App;

class ConstApp {
    const NUMBER_PER_PAGE = 12;
    const NUMBER_CHARACTERS_NEW_CONTENT = 120;
    const NUMBER_CHARACTERS_LIMIT_TITLE = 100;
    const NUMBER_CHARACTERS_LIMIT_NEWS = 150;
    const NUMBER_CHARACTERS_TITLE_LET_THAN = 10;
    const NUMBER_PER_PAGES_SCHEDULE = 10;
}
?>